### ISSUE TITLE
React SDK: Contract Reverted on `mintAndRegisterIpAssetWithPilTerms`

### ISSUE THREAD

**Issue by jacob-tucker** [storyprotocol/sdk#220]
**Describe the bug**
When using the React SDK, I am getting an issue using `mintAndRegisterIpAssetWithPilTerms`.

Here is my code:
```
export default function Test() {
    const { mintAndRegisterIpAssetWithPilTerms } = useIpAsset();

   const response = await mintAndRegisterIpAssetWithPilTerms({
       nftContract: "0xd516482bef63Ff19Ed40E4C6C2e626ccE04e19ED", // your NFT contract address
       pilType: PIL_TYPE.NON_COMMERCIAL_REMIX,
       metadata: {
          metadataURI: 'test-uri', // uri of IP metadata
          metadataHash: toHex('test-metadata-hash', { size: 32 }), // hash of IP metadata
          nftMetadataHash: toHex('test-nft-metadata-hash', { size: 32 }), // hash of NFT metadata
       },
       txOptions: { waitForTransaction: true }
});
}
```

And I get the following errors:
<img width="414" alt="Screenshot 2024-07-17 at 1 58 29 AM" src="https://github.com/user-attachments/assets/e60fec02-dab6-4591-a1a7-4549d03ca2e1">
<img width="412" alt="Screenshot 2024-07-17 at 1 58 34 AM" src="https://github.com/user-attachments/assets/fe5b46c8-0b6b-442e-840b-729832f9245b">

**Comment by bonnie57** [comment]
Hi @jacob-tucker , The reason is that `defaultLicenseTermsId` in the contract have changed into the no commercial license instead of empty. So a new ipId will have default license terms id of no commercial . And `mintAndRegisterIpAssetWithPilTerms` pass  `PIL_TYPE.NON_COMMERCIAL_REMIX` (default license terms id), it will throw error because defaultLicenseTermsId have attached. Current wait for fixing bug about commercial license in spg, and SDK will do the changes:
- remove no commercial related method
- remove no commercial license of pilType
- add mintAndRegisterIp in spg (it is backup for mintAndRegisterIpAssetWithPilTerms with no commercial )

**Comment by bonnie57** [comment]
There are some updates I want to let you know:

The `default license term `is subject to change and can be `equated` with the `no commercial license term `when calling `registerNonComSocialRemixingPIL` in the SDK. Therefore, we need to check if it is attached before calling hasIpAttachedLicenseTerms in both the SDK and SPG.

According to the current implementation, the SDK already performs this check. However, `SPG` needs to add this check in the `_registerPILTermsAndAttach` method. The SDK will maintain the no commercial license term. cc: @jacob-tucker @edisonz0718
